// Fixtures transcribed exactly from tests/acceptance/live/voice-smoke.test.ts at 407af7d.
export const SHA = "a".repeat(40);

export const inboundConversationTurn = {
  outcome: "voice_sent",
  committedUserEventId: "01j00000000000000000000001",
  sentAssistantEventId: "01j00000000000000000000004",
  deliveryId: null,
  deliveredAssistantEventId: null,
};

export const inboundEvidence = {
  schemaVersion: "1.3",
  generatorVersion: "0.1.0",
  status: "passed",
  scenario: "inbound",
  manifestKey: "inbound_call",
  commitSha: SHA,
  correlationId: "01j00000000000000000000000",
  startedAt: "2026-08-29T12:00:00.000Z",
  endedAt: "2026-08-29T12:01:00.000Z",
  terminalState: "completed",
  eventIds: [inboundConversationTurn.committedUserEventId, inboundConversationTurn.sentAssistantEventId],
  authenticatedTurns: 20,
  authenticationMode: "owner_passphrase",
  ownerStepUpOutcome: "verified",
  ownerStepUpPromptCount: 1,
  ownerStepUpAttemptCount: 1,
  callerIdAttestation: "passed_a",
  ownerCallerIdPolicy: "passphrase_always",
  ownerAuthorityGranted: true,
  ownerStepUpBeforeFirstModelTurn: true,
  interruptions: 1,
  firstAudibleMs: Array(20).fill(3_000),
  interruptionStopMs: [900],
  persistenceVerified: true,
  recallVerified: true,
  cleanHangup: true,
  sttProvider: "Deepgram",
  sttModel: "nova-3-general",
  ttsProvider: "Google",
  ttsVoice: "en-US-Journey-O",
  signedWssHandshake: "exact-configured-url",
  dtmfDelivery: "verified",
  statusCallbackSchema: "verified",
  relayEndedCallbackSchema: "verified",
  assistantOutputEvidence: "sent_to_provider_only",
  assistantHistoryCommitted: false,
  conversationTurnResult: inboundConversationTurn,
};

const commonEvidence = {
  schemaVersion: "1.3",
  generatorVersion: "0.1.0",
  status: "passed",
  commitSha: SHA,
  correlationId: "01j00000000000000000000002",
  startedAt: "2026-08-29T13:00:00.000Z",
  endedAt: "2026-08-29T13:01:00.000Z",
  eventIds: ["01j00000000000000000000003"],
};

export const unauthorizedEvidence = {
  ...commonEvidence,
  scenario: "unauthorized-caller",
  manifestKey: "unauthorized_caller",
  terminalState: "rejected",
  authenticatedTurns: 0,
  authenticationAttempts: 0,
  conversationRelaySessions: 0,
  pinPromptCount: 0,
  pinAttemptCount: 0,
  modelRequests: 0,
  personalContextReads: 0,
};

export const outboundAnswerEvidence = {
  ...commonEvidence,
  scenario: "outbound-answer",
  manifestKey: "outbound_answer",
  correlationId: "01j00000000000000000000005",
  terminalState: "completed",
  authenticatedTurns: 1,
  authenticationMode: "owner_passphrase",
  ownerStepUpOutcome: "verified",
  ownerStepUpPromptCount: 1,
  ownerStepUpAttemptCount: 1,
  callerIdAttestation: "not_applicable",
  ownerCallerIdPolicy: "passphrase_always",
  ownerAuthorityGranted: true,
  ownerStepUpBeforeFirstModelTurn: true,
  recipientAuthenticated: true,
  neutralGreetingBeforeAuthentication: true,
  purposeDisclosedAfterAuthentication: true,
  sttProvider: "Deepgram",
  sttModel: "nova-3-general",
  ttsProvider: "Google",
  ttsVoice: "en-US-Journey-O",
  signedWssHandshake: "exact-configured-url",
  dtmfDelivery: "verified",
  statusCallbackSchema: "verified",
  relayEndedCallbackSchema: "verified",
  assistantOutputEvidence: "sent_to_provider_only",
  assistantHistoryCommitted: false,
  eventIds: ["01j00000000000000000000006", "01j00000000000000000000007"],
  conversationTurnResult: {
    outcome: "voice_sent",
    committedUserEventId: "01j00000000000000000000006",
    sentAssistantEventId: "01j00000000000000000000007",
    deliveryId: null,
    deliveredAssistantEventId: null,
  },
};

export const outboundNoAnswerEvidence = {
  ...commonEvidence,
  scenario: "outbound-no-answer",
  manifestKey: "outbound_no_answer",
  correlationId: "01j00000000000000000000008",
  terminalState: "no-answer",
  authenticationMode: "owner_passphrase",
  ownerStepUpOutcome: "not_started",
  ownerStepUpPromptCount: 0,
  ownerStepUpAttemptCount: 0,
  callerIdAttestation: "not_applicable",
  ownerCallerIdPolicy: "passphrase_always",
  ownerAuthorityGranted: false,
  callAttempts: 1,
  recipientAuthenticated: false,
  purposeDisclosed: false,
  privateMessageLeft: false,
  modelRequests: 0,
  personalContextReads: 0,
  statusCallbackSchema: "verified",
  eventIds: ["01j00000000000000000000009"],
};

export const ownerStepUpRefusedEvidence = {
  ...commonEvidence,
  scenario: "owner-step-up-refused",
  manifestKey: "owner_step_up_refused",
  correlationId: "01j0000000000000000000000a",
  terminalState: "rejected",
  eventIds: ["01j0000000000000000000000b"],
  authenticatedTurns: 0,
  authenticationMode: "owner_passphrase",
  ownerStepUpOutcome: "refused",
  ownerStepUpPromptCount: 3,
  ownerStepUpAttemptCount: 3,
  ownerStepUpRepromptCount: 0,
  ownerStepUpRejectionReason: "attempts_exhausted",
  callerIdAttestation: "other",
  ownerCallerIdPolicy: "passphrase_always",
  ownerAuthorityGranted: false,
  modelRequests: 0,
  personalContextReads: 0,
  rejectionRowCount: 1,
  rejectionDeliveryRowCount: 1,
  ownerAlertDisposition: "sent",
};

export const failureEvidence = {
  ...commonEvidence,
  scenario: "failure-callbacks",
  manifestKey: "voice_failure_callbacks",
  correlationId: "01j0000000000000000000000c",
  terminalState: "failed",
  modelFailureHandled: true,
  websocketFailureHandled: true,
  callbackFailureHandled: true,
  unauthorizedCallbackCreated: false,
  statusCallbackSchema: "verified",
  relayEndedCallbackSchema: "verified",
  safeErrorCategories: ["model_unavailable", "relay_closed", "callback_rejected"],
  eventIds: ["01j0000000000000000000000d"],
  conversationTurnResult: {
    outcome: "failed",
    committedUserEventId: "01j0000000000000000000000d",
    sentAssistantEventId: null,
    deliveryId: null,
    deliveredAssistantEventId: null,
  },
  modelFailureCode: "model_failed",
  modelFailureCategory: "provider",
};

export const AUDIT_TIME = new Date("2026-08-30T00:00:00.000Z");

export const completeSet = [
  inboundEvidence,
  unauthorizedEvidence,
  outboundAnswerEvidence,
  outboundNoAnswerEvidence,
  ownerStepUpRefusedEvidence,
  failureEvidence,
];
