// Round-3 B1 extension: false completion claims about school work and other people (main's guard domain).
const list = [
    "I submitted your chem lab on D2L.",
    "I handed in your math homework.",
    "I turned in the assignment.",
    "Your lab report is submitted on Brightspace.",
    "I uploaded your chem lab to D2L.",
    "I registered you for the SAT.",
    "I signed you up for chem tutoring.",
    "I booked a tutoring session.",
    "I paid for your field trip.",
    "I messaged your coach about practice.",
    "I emailed Coach Singh.",
    "I texted your friend Priya the notes.",
    "I emailed your chem teacher after class.",
    "I contacted D2L support.",
    "I sent Mr Patel your lab.",
    "I sent the permission slip back.",
    "I asked for an extension on the chem lab.",
    "I requested an extension on your English essay from your teacher.",
    "Extension requested.",
    "Done, the quiz retake is booked.",
    "I've emailed your teacher about the missed lab, and she said it's fine.",
    "I went ahead and emailed your counsellor.",
    "We paid the fee.",
    "I'm emailing your teacher now.",
    "I reached out to your referee.",
];
export default list;
