const spec = [];
const add = (name, file, find, replace, testFile, testName) => spec.push({ name, file, find, replace, testFile, testName });
const core = (name, find, replace, testName) => add(name, "probe.js", find, replace, "probe.test.js", testName);
const wiring = (name, file, find, replace, testName) => add(name, file, find, replace, "wiring.test.js", testName);
const manifestTest = "It grants only the LDSB host and storage in Manifest V3.";
const networkTest = "It permits only the probe read fetch call across every runtime script and popup asset.";
const shapeTest = "It reports nested field presence and nulls without printing values or unknown keys.";
const shapeKinds = "It distinguishes empty arrays, empty objects, lists and Objects envelopes.";
const injectionTest = "It refuses unknown routes and path injection before calling fetch.";
const getTest = "It hard-codes GET and forbids redirect following and request bodies.";
const redirectTest = "It refuses redirected and opaque responses without reading their bodies.";
const traversalTest = "It discovers all accessible enrollment pages and probes every folder through the student route.";
const pagingTest = "It stops missing or repeated enrollment bookmarks without following response URLs.";
const popupSenderTest = "It accepts probe commands only from this extension popup.";
const contentSenderTest = "It accepts content reads only from its extension and never from a tab sender.";

wiring("manifest host scope", "manifest.json", '"host_permissions": ["https://ldsb.elearningontario.ca/*"]', '"host_permissions": ["https://*/*"]', manifestTest);
wiring("manifest permission scope", "manifest.json", '"permissions": ["storage"]', '"permissions": ["storage", "alarms"]', manifestTest);
wiring("content host scope", "manifest.json", '"matches": ["https://ldsb.elearningontario.ca/*"]', '"matches": ["https://*/*"]', manifestTest);
wiring("content isolation", "manifest.json", '"world": "ISOLATED"', '"world": "MAIN"', manifestTest);
wiring("connect scope", "manifest.json", 'connect-src https://ldsb.elearningontario.ca', 'connect-src *', manifestTest);
core("H1 literal API host", 'const HOST = "https://ldsb.elearningontario.ca";', 'const HOST = "https://invalid.example";', "It pins every route to the literal LDSB HTTPS origin.");
wiring("H9 popup fetch", "popup.js", 'const run =', 'fetch("https://invalid.example");\nconst run =', networkTest);
wiring("popup HTML EventSource", "popup.html", '</body>', '<script>new EventSource("https://invalid.example");</script>\n</body>', networkTest);
wiring("remote worker import", "worker.js", 'importScripts("probe.js", "controller.js");', 'importScripts("https://invalid.example/script.js");', networkTest);
wiring("second transport fetch call", "probe.js", 'response = await fetchImpl(url, {', 'await fetchImpl(url, {});\n      response = await fetchImpl(url, {', networkTest);
core("schema key allowlist", 'FIELDS.has(key) ? key : "<other field>"', 'key', shapeTest);
core("scalar redaction", 'shape = "scalar (redacted)"', 'shape = String(body)', shapeKinds);
core("null field distinction", 'child === null ? "null" : "set"', '"set"', shapeTest);
core("array shape distinction", 'if (Array.isArray(body)) shape', 'if (false) shape', shapeKinds);
core("null body distinction", 'else if (body === null)', 'else if (false)', shapeKinds);
core("Objects envelope distinction", 'else if (Array.isArray(body.Objects))', 'else if (false)', shapeKinds);
core("nested array traversal", 'if (Array.isArray(value))', 'if (false)', shapeTest);
core("nested object traversal", 'value !== null && typeof value === "object"', 'false', shapeTest);
core("route allowlist", 'if (!Object.hasOwn(LABELS, route)) throw new Error("invalid-route");', '', injectionTest);
core("identifier validation", 'if (!/^[0-9]{1,20}$/.test(String(value))) throw new Error("invalid-identifier");', '', injectionTest);
core("GET only", 'method: "GET"', 'method: "POST"', getTest);
core("no redirect follow", 'redirect: "manual"', 'redirect: "follow"', getTest);
core("session credentials", 'credentials: "include"', 'credentials: "omit"', getTest);
core("request timeout", 'AbortSignal.timeout(15000)', 'AbortSignal.timeout(150000)', "It supplies a fifteen-second abort signal to the fetch transport.");
core("opaque response refusal", 'response.status === 0 || ', '', redirectTest);
core("redirected response refusal", 'response.redirected || ', '', redirectTest);
core("3xx response refusal", '(response.status >= 300 && response.status < 400)', 'false', redirectTest);
core("HTML body refusal", 'if (!/^application\\/(?:[\\w.+-]+\\+)?json\\b/i.test(response.headers.get("content-type") ?? ""))', 'if (false)', "It refuses HTML and missing content types without reading web pages.");
core("successful status discovery", 'result.status >= 200 && result.status < 300 && !result.error', '!result.error', "It does not treat refused enrollments as a successful discovery.");
core("transport error discovery refusal", '&& !result.error', '', "It stops discovery when a transport error accompanies a nominal success status.");
core("enrollment shape check", 'if (!Array.isArray(result.body?.Items)) return "enrollments-shape-unexpected";', '', "It reports unexpected enrollment shapes instead of claiming there are no courses.");
core("access eligibility", 'if (item?.Access?.CanAccess === true)', 'if (true)', traversalTest);
core("enrollment pagination continuation", 'if (result.body.PagingInfo?.HasMoreItems !== true) break;', 'break;', traversalTest);
core("bookmark type check", 'typeof bookmark !== "string" || ', '', pagingTest);
core("empty bookmark check", 'bookmark.length === 0 || ', '', pagingTest);
core("repeated bookmark check", 'bookmarks.has(bookmark)', 'false', pagingTest);
core("folder status check", 'if (!isSuccess(folders)) continue;', '', "It continues unrelated routes after refusals and does not discover folders from errors.");
core("folder shape check", 'if (!Array.isArray(folders.body))', 'if (false)', "It reports unexpected folder shapes as unprobed submissions.");
core("student submission route", '/submissions/mysubmissions/', '/submissions/', traversalTest);
wiring("run lock", "controller.js", 'if (active) return;', '', "It prevents a duplicate click from starting a second concurrent pass.");
wiring("tab context choice", "controller.js", 'openTabs.length === 0 ? "background" : "content"', '"background"', "It runs open-tab requests through the content script and retains the background comparison.");
wiring("content transport branch", "controller.js", 'if (context === "content")', 'if (false)', "It runs open-tab requests through the content script and retains the background comparison.");
wiring("preflight error propagation", "controller.js", 'if (!report) throw new Error("probe-unavailable");', 'if (!report) return;', "It rejects a failed tab preflight instead of presenting an old report as a completed pass.");
wiring("before-fetch no-tab check", "controller.js", 'if ((await tabs()).length !== 0) throw new Error("context-changed");\n          const result', 'const result', "It interrupts a background pass when a D2L tab opens before a request.");
wiring("after-fetch no-tab check", "controller.js", 'if ((await tabs()).length !== 0) throw new Error("context-changed");\n          return result;', 'return result;', "It interrupts a background pass when a D2L tab opens during a request.");
wiring("popup extension identity", "controller.js", 'sender.id !== api.runtime.id || ', '', popupSenderTest);
wiring("popup source check", "controller.js", 'sender.url !== api.runtime.getURL("popup.html")', 'false', popupSenderTest);
wiring("popup command check", "controller.js", 'if (message?.type !== "RUN_PROBE") return false;', '', popupSenderTest);
wiring("content extension identity", "content.js", 'sender.id !== chrome.runtime.id || ', '', contentSenderTest);
wiring("content tab sender refusal", "content.js", 'sender.tab !== undefined', 'false', contentSenderTest);
wiring("content command check", "content.js", 'if (message?.type !== "D2L_READ") return false;', '', contentSenderTest);
export default spec;
